name: Python Test Coverage

on:
  workflow_call:
  workflow_dispatch:
 
permissions:
  contents: read

jobs:
  build-python-coverage:
    name: Enforce Python Unit Test Coverage
    runs-on: ubuntu-latest
    steps:

    - name: Checkout sources
      uses: actions/checkout@v3

    - uses: zlatko-ms/envarfiles@v3
      with:
        paths: ./conf/buildvars.properties

    - name: Setup Python ${{ env.PYTHON_VERSION }} interpreter
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Setup Python dependency modules
      run: |
        python -m pip install --upgrade pip
        pip install -r ./conf/python/build.txt -r ./conf/python/runtime.txt

    - name: Ensure Unit Test coverage is high enough 
      run: |
        # compute and display coverage
        python -m nose2 --with-coverage -F -s ${{ env.UNIT_TEST_DIR }} -t . 2> /tmp/coverage
        cat /tmp/coverage
        # get coverage metrics
        expectedTotal=${{ env.PYTHON_COVERAGE_MIN_TOTAL }}
        foundTotal=$(grep "TOTAL" /tmp/coverage | cut -f41 -d' ' | sed 's/\%//g')
        echo "[INFO] Global    code coverage expected=$expectedTotal found=$foundTotal"
        # acceptance
        if [ $foundTotal -lt $expectedTotal ]; then
          echo "[ERROR] Current global coverage is below minimal treshold !"
          exit 255
        fi

    

  