name: Python Build

on:
  workflow_call:
  workflow_dispatch:
 
permissions:
  contents: read

jobs:
  
  coding:
    uses: ./.github/workflows/build-coding-style.yml

  unittest:
    uses: ./.github/workflows/build-unit-tests.yml

  coverage:
    uses: ./.github/workflows/build-coverage-check.yml

  integration:
    needs: [ coding, unittest , coverage ]
    uses: ./.github/workflows/build-it.yml
    

  
